repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: format
        name: format
        entry: make format
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: test
        name: test
        entry: make test
        language: system
        pass_filenames: false
        stages:
          - push
  - repo: local
    hooks:
      - id: export-packages
        name: export-packages
        entry: make poetry-export
        language: system
        pass_filenames: false
        stages:
          - push
