repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: format
        name: format
        entry: make lint
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: format-tf
        name: format-tf
        entry: sh -c 'terraform fmt --check terraform/'
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: test
        name: test
        entry: make test
        language: system
        pass_filenames: false
        stages:
          - push
