name: Tests

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install poetry
      uses: Gr1N/setup-poetry@v9
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Install dependencies
      run: poetry install
    - name: Run black check
      run: poetry run black -l 120 --check ./modelmind
    - name: Run mypy check
      run: poetry run mypy --ignore-missing-imports ./modelmind
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install Poetry
      uses: Gr1N/setup-poetry@v9
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Install dependencies
      run: poetry install
    - name: Run pytest check
      run: poetry run pytest -vv --cov="modelmind" .
      env:
        MODELMIND_ADMIN_HOST: "0.0.0.0"
